### ISSUE TITLE
Linux下编译缺少相关头文件

### ISSUE THREAD

**Issue by Freelifeww** [ireader/avcodec#11]

**Comment by Freelifeww** [comment]
In file included from src/avpkt2bs.c:1:
./include/avpkt2bs.h:7:10: fatal error: mpeg4-aac.h: 没有那个文件或目录
    7 | #include "mpeg4-aac.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
-e      CREATE  avpbs-vpx.d
src/avpbs-vpx.c:2:10: fatal error: webm-vpx.h: 没有那个文件或目录
    2 | #include "webm-vpx.h"
      |          ^~~~~~~~~~~~
compilation terminated.
-e      CREATE  avpbs-opus.d
src/avpbs-opus.c:2:10: fatal error: opus-head.h: 没有那个文件或目录
    2 | #include "opus-head.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
-e      CREATE  avpbs-mp3.d
src/avpbs-mp3.c:2:10: fatal error: mp3-header.h: 没有那个文件或目录
    2 | #include "mp3-header.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
-e      CREATE  avpbs-h266.d
src/avpbs-h266.c:2:10: fatal error: mpeg4-avc.h: 没有那个文件或目录
    2 | #include "mpeg4-avc.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
-e      CREATE  avpbs-h265.d
src/avpbs-h265.c:3:10: fatal error: mpeg4-avc.h: 没有那个文件或目录
    3 | #include "mpeg4-avc.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
-e      CREATE  avpbs-h264.d
src/avpbs-h264.c:3:10: fatal error: mpeg4-avc.h: 没有那个文件或目录
    3 | #include "mpeg4-avc.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
-e      CREATE  avpbs-g7xx.d
-e      CREATE  avpbs.d
-e      CREATE  avpbs-av1.d
src/avpbs-av1.c:2:10: fatal error: aom-av1.h: 没有那个文件或目录
    2 | #include "aom-av1.h"
      |          ^~~~~~~~~~~
compilation terminated.
-e      CREATE  avpbs-aac.d
src/avpbs-aac.c:2:10: fatal error: mpeg4-aac.h: 没有那个文件或目录
    2 | #include "mpeg4-aac.h"
      |          ^~~~~~~~~~~~~

**Comment by Freelifeww** [comment]
请教下，是否自己操作问题，感谢

**Comment by ireader** [comment]
请下载 https://github.com/ireader/media-server 到 avcodec同级目录下。

**Comment by Freelifeww** [comment]
> 请下载 https://github.com/ireader/media-server 到 avcodec同级目录下。
谢谢，我自己下载目录问题，已经解决。感谢
