### ISSUE TITLE
g711-encoder.c:232:21: error: 'ENOMEM' undeclared (first use in this function)

### ISSUE THREAD

**Issue by zhangzj03** [ireader/avcodec#2]
source/g711-encoder.c: In function 'g711_encode':
source/g711-encoder.c:232:21: error: 'ENOMEM' undeclared (first use in this function)
             return -ENOMEM;
                     ^~~~~~
when i make all under avcodec subfolder

**Comment by ireader** [comment]
#include <errno.h>
